In [1]:
import pandas as pd
import numpy as np


In [2]:
trainData = pd.read_csv('/home/roshan/Documents/FreelanceWork/Work/MathewCoeff/Train_data.csv')
testData = pd.read_csv('/home/roshan/Documents/FreelanceWork/Work/MathewCoeff/Test_data.csv')

In [3]:
trainData.head()

B1     B2     B3     B4     B5     B6     B7     B8     B9    B10  \
0  5.778  7.550  3.935  0.000  5.903  0.000  5.903  3.935  1.968  0.000   
1  5.804  6.125  6.373  0.000  4.248  2.124  4.248  6.373  0.000  8.497   
2  7.256  6.044  4.242  0.000  2.121  0.000  0.000  2.121  0.000  2.121   
3  8.155  5.772  0.000  2.065  4.129  0.000  0.000  8.258  2.065  2.065   
4  5.821  5.705  8.746  2.187  2.187  4.372  0.000  0.000  2.187  0.000   

   ...    B12221  B12222  B12223  B12224  B12225  B12226  B12227  B12228  \
0  ...         0       0       1       0       0       0       0       0   
1  ...         0       0       0       0       0       0       0       0   
2  ...         0       0       0       1       0       0       0       0   
3  ...         0       0       0       0       0       0       0       0   
4  ...         0       0       0       0       0       0       0       0   

   B12229  Class  
0       0      1  
1       0      1  
2       0      1  
3       0      1  
4       0      1  

[5 rows x 12230 columns]

In [4]:
testData.head()

B1     B2     B3     B4     B5     B6      B7     B8     B9    B10  \
0  5.658  5.571  4.432  2.217  2.217  2.217   2.217  6.649  0.000  4.432   
1  7.011  6.244  0.000  2.246  6.739  6.739   0.000  8.985  4.492  4.492   
2  6.825  6.991  0.000  0.000  2.092  0.000  14.641  4.183  2.092  2.092   
3  5.797  5.079  0.000  2.263  2.263  0.000   4.525  6.787  2.263  2.263   
4  5.156  6.621  0.000  0.000  2.279  2.279   2.279  2.279  4.558  0.000   

   ...    B12221  B12222  B12223  B12224  B12225  B12226  B12227  B12228  \
0  ...         0       0       0       1       0       0       0       0   
1  ...         0       0       0       0       0       0       0       0   
2  ...         0       0       0       0       0       0       0       0   
3  ...         0       0       0       0       0       0       0       0   
4  ...         0       0       0       0       0       0       0       0   

   B12229  Class  
0       0      1  
1       0      1  
2       0      1  
3       1      1  
4       0      1  

[5 rows x 12230 columns]

In [5]:
trainLabel = trainData.loc[:,'Class']

In [6]:
testLabel = testData.loc[:,'Class']

In [7]:
trainData = trainData.drop('Class',axis=1)
testData = testData.drop('Class',axis=1)

In [10]:
testLabel.describe()

count    168.000000
mean       0.166667
std        0.373792
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: Class, dtype: float64

In [14]:
trainSTD = trainData.std()

In [12]:
trainData['B12207'].describe()

count    2035.000000
mean        0.018673
std         0.138985
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         2.000000
Name: B12207, dtype: float64

In [13]:
np.histogram(trainData['B12207'])

(array([1998,    0,    0,    0,    0,   36,    0,    0,    0,    1]),
 array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ]))

In [15]:
trainSTD.head()

B1    1.069641
B2    1.124221
B3    2.799909
B4    1.720922
B5    2.739137
dtype: float64

In [20]:
len(trainSTD.loc[trainSTD<0.05])

5290

In [21]:
trainSTD.loc[trainSTD<0.05]

B48       0.000000
B49       0.000000
B50       0.000000
B51       0.000000
B52       0.000000
B53       0.000000
B54       0.000000
B55       0.000000
B60       0.000000
B64       0.031342
B71       0.000000
B72       0.000000
B84       0.000000
B91       0.000000
B96       0.000000
B97       0.000000
B98       0.000000
B99       0.000000
B100      0.000000
B101      0.000000
B102      0.000000
B103      0.000000
B104      0.000000
B106      0.000000
B111      0.049519
B119      0.000000
B126      0.000000
B129      0.000000
B130      0.000000
B131      0.000000
            ...   
B9704     0.000000
B9725     0.000000
B9726     0.000000
B9733     0.000000
B9758     0.000000
B9759     0.000000
B9764     0.000000
B9780     0.000000
B9782     0.000000
B9788     0.000000
B9791     0.000000
B9792     0.000000
B9793     0.000000
B9797     0.000000
B9809     0.000000
B9816     0.000000
B9826     0.000000
B10083    0.049519
B10168    0.044302
B10206    0.031342
B10273    0.038376
B10296    0.

In [25]:
np.histogram(trainData['B12105'])

(array([2030,    0,    0,    0,    0,    0,    0,    0,    0,    5]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [23]:
len(trainData)

2035